environment:
  RTOOLS_ARCH: x86_64
  PfxUri:
    secure: z+vP1iY4odY07BV7v+yfuA2MBKQFFLGokZoefPhz22ewYZAm6XZ8jsdphTFYkn7L
  CertPassword:
    secure: nwSwtaLCl6Xo5sfqKLvO30aFFGCgjGJ2GKTqS33zkJg=
  SignTool: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe
  build_installer: true

install:
    - ps: Import-Module .\scripts.ps1
    - ps: InstallInno
    - ps: InstallMiktex
    - ps: InstallRtoolsExe
    - ps: SetTimezone

build_script:
  - C:\rtools40\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build.sh"

after_build:
  - ps: SignFiles "R-devel-win.exe"

artifacts:
  - path: "R-devel-win.exe"
    name: installer
  - path: build.log
    name: buildlog

