on:
  push:
  pull_request:

name: Test quick-build script

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Run quick-build script
        run: $(cygpath ${GITHUB_WORKSPACE})/quick-build.sh
        shell: c:\rtools40\usr\bin\bash.exe --login {0}
